=== MuhamadFahmi/tugas_webservice2/tugas_web_service2/lemari.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    
    <xs:element name="penjualan">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="barang"/>
            </xs:sequence>
           
        </xs:complexType>
    </xs:element>
    <xs:element name="barang">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="jenis"/>
                <xs:element ref="jumlah"/>
                <xs:element ref="harga"/>
                <xs:element ref="reseller"/>
                <xs:element ref="pemilik"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="jenis" type="xs:string"/>
    <xs:element name="jumlah" type="xs:integer"/>
    <xs:element name="harga" type="xs:integer"/>
    <xs:element name="reseller">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="pt"/>
                <xs:element ref="kode"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="pt" type="xs:string"/>
    <xs:element name="kode" type="xs:integer"/>
    <xs:element name="pemilik">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nama"/>
                <xs:element ref="nomor"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="nama" type="xs:NCName"/>
    <xs:element name="nomor" type="xs:integer"/>
</xs:schema>

=== MuhamadFahmi/tugas_webservice2/tugas_web_service2/lemari.xml
<?xml version="1.0" encoding="UTF-8"?>
<penjualan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="lemari.xsd">
    <barang>
        <jenis>lemari anak</jenis>
        <jumlah>4</jumlah>
        <harga>150000</harga>
        <reseller>
            <pt>olympic</pt>
            <kode>1154049</kode>
        </reseller>
        <pemilik>
            <nama>fahmi</nama>
            <nomor>1</nomor>
        </pemilik>
    </barang>
    <barang>
        <jenis>lemari pakaian</jenis>
        <jumlah>5</jumlah>
        <harga>500000</harga>
       <reseller>
            <pt>hotel setiabudhi</pt>
            <kode>11540499</kode>
        </reseller>
        <pemilik>
            <nama>fahmi</nama>
            <nomor>13</nomor>
        </pemilik>
    </barang>
</penjualan>
